# Generated by Django 2.2.1 on 2019-05-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=254)),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('c', 'curtir'), ('a', 'amar'), ('r', 'rir'), ('i', 'impressionar'), ('t', 'triste'), ('grr', 'irritar')], max_length=1)),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=30)),
                ('data_de_nascimento', models.DateField(verbose_name='Nascimento')),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postagens', models.ManyToManyField(to='blog.Postagem')),
            ],
        ),
        migrations.AddField(
            model_name='postagem',
            name='reacoes',
            field=models.ManyToManyField(to='blog.Reacao'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254)),
                ('contatos', models.ManyToManyField(related_name='_perfil_contatos_+', to='blog.Perfil')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to='blog.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=254)),
                ('data', models.DateTimeField()),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Perfil')),
            ],
        ),
    ]
